<a href="https://colab.research.google.com/github/Wajid0005/CAMPUS-X-notebooks/blob/main/Copy_of_session_18_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [ ]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
df.head(2)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3

In [ ]:
teams = df.Team.unique()
on_target_percentage = {}
for team in teams:
  total_attempts = df[df['Team']== team]['Total Attempts'].sum()
  total_on_target = df[df['Team'] == team]['On Target'].sum()
  on_target_percentage[team] = round(total_on_target/ total_attempts*100, 2)

dict(sorted(on_target_percentage.items(), key = lambda x: x[1], reverse=True))

{'Costa Rica': np.float64(54.55),
 'Cameroon': np.float64(51.85),
 'Ecuador': np.float64(48.15),
 'Argentina': np.float64(46.15),
 'Brazil': np.float64(45.56),
 'England': np.float64(45.0),
 'Portugal': np.float64(40.32),
 'Ghana': np.float64(40.0),
 'Netherlands': np.float64(39.02),
 'Korea Republic': np.float64(36.73),
 'Australia': np.float64(36.0),
 'Mexico': np.float64(34.88),
 'France': np.float64(34.65),
 'Germany': np.float64(34.33),
 'Croatia': np.float64(33.73),
 'Spain': np.float64(32.69),
 'Belgium': np.float64(32.35),
 'Serbia': np.float64(32.26),
 'Iran': np.float64(31.43),
 'Uruguay': np.float64(31.25),
 'United States': np.float64(31.11),
 'Saudi Arabia': np.float64(31.03),
 'Senegal': np.float64(30.77),
 'Denmark': np.float64(30.56),
 'Switzerland': np.float64(30.56),
 'Japan': np.float64(30.23),
 'Wales': np.float64(29.17),
 'Qatar': np.float64(28.57),
 'Morocco': np.float64(28.33),
 'Tunisia': np.float64(26.67),
 'Poland': np.float64(25.0),
 'Canada': np.float64(17.65)}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
df.head(5)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

In [ ]:
df['Team'].value_counts().rank(method = 'first')

Team
France            29.0
Argentina         30.0
Croatia           31.0
Morocco           32.0
Brazil            25.0
Portugal          26.0
England           27.0
Netherlands       28.0
Spain             17.0
Japan             18.0
Switzerland       19.0
Korea Republic    20.0
Australia         21.0
Poland            22.0
Senegal           23.0
United States     24.0
Mexico             1.0
Saudi Arabia       2.0
Denmark            3.0
Tunisia            4.0
Iran               5.0
Ecuador            6.0
Qatar              7.0
Wales              8.0
Canada             9.0
Belgium           10.0
Costa Rica        11.0
Germany           12.0
Uruguay           13.0
Cameroon          14.0
Ghana             15.0
Serbia            16.0
Name: count, dtype: float64

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
#1
info = df.info()
#2
des =df.describe()
#3
na = df.isna().sum()
#4
print(df.shape)
df.drop_duplicates(inplace= True)
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB
(128, 38)
(128, 38)

In [ ]:
#5
df.drop(['Sl. No', 'Match No.', 'Pts'],axis= 1, inplace = True)

In [ ]:
df.columns

Index(['Team', 'Against', 'Group', 'Goal', 'Possession (%)',
       'Inside Penalty Area', 'Outside Penalty Area', 'Assists',
       'Total Attempts', 'On Target', 'Off Target', 'Target in Penalty',
       'Target from Outside', 'Left Channel', 'Left Inside Channel',
       'Central Channel', 'Right Inside Channel', 'Right Channel',
       'Receptions MD', 'Receptions D', 'Attempted Line Breaks',
       'Completed Line Breaks', 'Attempted Defensive Line Breaks',
       'Completed Defensive Line Breaks', 'Yellow Cards', 'Red Cards',
       'Fouls Against', 'Offsides', 'Passes', 'Passes Completed', 'Crosses',
       'Crosses Completed', 'Corners', 'Free Kicks', 'Penalties Scored'],
      dtype='object')

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
df['Rank'] = df['Team'].value_counts().rank(method = 'first')

In [ ]:
team_appearance_counts = df['Team'].value_counts()
team_ranks_series = team_appearance_counts.rank(method = 'first').astype(np.int16)
df['Rank'] = df['Team'].map(team_ranks_series)

In [ ]:
df.Rank

0       7
1       6
2      27
3       5
4      23
       ..
123    32
124    31
125    32
126    30
127    29
Name: Rank, Length: 128, dtype: int16

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Team                             128 non-null    object
 1   Against                          128 non-null    object
 2   Group                            128 non-null    object
 3   Goal                             128 non-null    int64
 4   Possession (%)                   128 non-null    int64
 5   Inside Penalty Area              128 non-null    int64
 6   Outside Penalty Area             128 non-null    int64
 7   Assists                          128 non-null    int64
 8   Total Attempts                   128 non-null    int64
 9   On Target                        128 non-null    int64
 10  Off Target                       128 non-null    int64
 11  Target in Penalty                128 non-null    int64
 12  Target from Outside              128 non-null    int64
 13  Left Channel                     128 non-null    int64
 14  Left Inside Channel              128 non-null    int64
 15  Central Channel                  128 non-null    int64
 16  Right Inside Channel             128 non-null    int64
 17  Right Channel                    128 non-null    int64
 18  Receptions MD                    128 non-null    int64
 19  Receptions D                     128 non-null    int64
 20  Attempted Line Breaks            128 non-null    int64
 21  Completed Line Breaks            128 non-null    int64
 22  Attempted Defensive Line Breaks  128 non-null    int64
 23  Completed Defensive Line Breaks  128 non-null    int64
 24  Yellow Cards                     128 non-null    int64
 25  Red Cards                        128 non-null    int64
 26  Fouls Against                    128 non-null    int64
 27  Offsides                         128 non-null    int64
 28  Passes                           128 non-null    int64
 29  Passes Completed                 128 non-null    int64
 30  Crosses                          128 non-null    int64
 31  Crosses Completed                128 non-null    int64
 32  Corners                          128 non-null    int64
 33  Free Kicks                       128 non-null    int64
 34  Penalties Scored                 128 non-null    int64
 35  Rank                             128 non-null    int16
dtypes: int16(1), int64(32), object(3)
memory usage: 35.4+ KB

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
URL1 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"

URL2 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv"

DATA1 = pd.read_csv(URL1)
DATA2 = pd.read_csv(URL2)

DATA1['Age'].isna().sum()
DATA1.dropna(subset = ['Age'], inplace = True)
DATA1['Age'].isna().sum()

np.int64(0)

In [ ]:
DATA2['Age'].isna().sum()

np.int64(0)

In [ ]:
DATA2['Age'].fillna(20, inplace = True)

/tmp/ipython-input-473/1694881881.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  DATA2['Age'].fillna(20, inplace = True)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
ipl_matches = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv")
ipl_matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
ipl_matches['Team1'].replace({"Delhi Daredevils":"Delhi Capitals","Kings XI Punjab":"Punjab Kings","Rising Pune Supergiants":"Rising Pune Supergiant"}, inplace = True)
ipl_matches['Team2'].replace({"Delhi Daredevils":"Delhi Capitals","Kings XI Punjab":"Punjab Kings","Rising Pune Supergiants":"Rising Pune Supergiant"}, inplace = True)

In [ ]:
ipl_matches['Team1'].unique()
matches = ipl_matches.copy()

In [ ]:
df = matches[~matches.WinningTeam.isna()]
new_df =pd.DataFrame()
teams = df.Team1.unique()
data = []
for team in teams:
  played = df[(df.Team1 == team) | (df.Team2 == team)].shape[0]
  wins = df[df.WinningTeam == team].shape[0]
  home_wins = df[(df.WinningTeam == team)| (df.Team1 == team)].shape[0] / df[df.Team1 == team].shape[0] * 100
  away_wins = df[(df.WinningTeam == team)| (df.Team2 == team)].shape[0] / df[df.Team2 == team].shape[0] * 100
  data.append([team, played, wins, home_wins, away_wins])
new_df[["Team", "Matches Played", "Wins", "Home Win%", "Away Win%"]] = data
print(new_df.sort_values(by = "Wins", ascending = False, inplace = True))

None

###`Q-7:` Venues with most "no result" matches.

In [ ]:
(ipl_matches['WonBy'] == 'NoResult').sum()

np.int64(0)

In [ ]:
ipl_matches[ipl_matches['WonBy'] == 'NoResult']

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

###`Q-8:` Player with most appearance in final match.

In [ ]:
final_matches = ipl_matches[(ipl_matches['MatchNumber'] == 'Final') & (ipl_matches['WonBy'] != 'NoResult')]

all_players = pd.Series(dtype='object')
for index, row in final_matches.iterrows():
    team1_players_str = row['Team1Players']
    team2_players_str = row['Team2Players']

    # Clean and split player names for Team1
    if isinstance(team1_players_str, str):
        team1_players = [p.strip(" '") for p in team1_players_str.strip('[]').split(', ')]
        all_players = pd.concat([all_players, pd.Series(team1_players)])

    # Clean and split player names for Team2
    if isinstance(team2_players_str, str):
        team2_players = [p.strip(" '") for p in team2_players_str.strip('[]').split(', ')]
        all_players = pd.concat([all_players, pd.Series(team2_players)])

most_frequent_player = all_players.value_counts().idxmax()
most_frequent_player_count = all_players.value_counts().max()

print(f"Player with most appearances in final matches: {most_frequent_player}")
print(f"Number of appearances: {most_frequent_player_count}")

Player with most appearances in final matches: MS Dhoni
Number of appearances: 10

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
data = ipl_matches.copy()
data.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
655,548355,Mumbai,2012-05-06,2012,49,Mumbai Indians,Chennai Super Kings,Wankhede Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,2.0,NaN,DR Smith,"['JEC Franklin', 'SR Tendulkar', 'RG Sharma', ...","['M Vijay', 'F du Plessis', 'SK Raina', 'DJ Br...",Asad Rauf,S Asnani
348,1082615,Pune,2017-04-22,2017,24,Rising Pune Supergiant,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,N,Rising Pune Supergiant,Wickets,6.0,NaN,MS Dhoni,"['AM Rahane', 'RA Tripathi', 'SPD Smith', 'MS ...","['DA Warner', 'S Dhawan', 'KS Williamson', 'MC...",AY Dandekar,A Deshmukh

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here