<a href="https://colab.research.google.com/github/Wajid0005/CAMPUS-X-notebooks/blob/main/nlp_data_collection_transformatio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HI I am doing my NLP course and this is my work for Data Preprocessing, I did this using AI as I know what to do

In [12]:
import pandas as pd

df = pd.read_csv("business_data.csv")

In [13]:
df

,headlines,description,content,url,category
0,Nirmala Sitharaman to equal Morarji Desai’s re...,With the presentation of the interim budget on...,"Sitharaman, the first full-time woman finance ...",https://indianexpress.com/article/business/bud...,business
1,"‘Will densify network, want to be at least no....","'In terms of market share, we aim to double it...",The merger of Tata group’s budget airlines Air...,https://indianexpress.com/article/business/avi...,business
2,Air India group to induct an aircraft every si...,Air India currently has 117 operational aircra...,The Air India group plans to induct one aircra...,https://indianexpress.com/article/business/avi...,business
3,Red Sea woes: Exporters seek increased credit ...,Rising attacks forced shippers to consider the...,Indian exporters have asked the central govern...,https://indianexpress.com/article/business/red...,business
4,Air India group to induct a plane every 6 days...,"Apart from fleet expansion, 2024 will also see...",The Air India group plans to induct one aircra...,https://indianexpress.com/article/business/avi...,business
...,...,...,...,...,...
1995,"Two official teams from India, EU to discuss c...",India raised these issues in the Trade and Tec...,India and the European Union have constituted ...,https://indianexpress.com/article/business/two...,business
1996,"Adani family sells $1 billion stake to GQG, ot...",The group's flagship Adani Enterprises Ltd saw...,US-based boutique investment firm GQG Partners...,https://indianexpress.com/article/business/com...,business
1997,Housing sales up 8% in April-June period acros...,Housing sales rose 8 per cent annually during ...,Housing sales rose 8 per cent annually during ...,https://indianexpress.com/article/business/hou...,business
1998,Spike in tomato prices temporary; rates will c...,The maximum price of Rs 122 per kg has been re...,The spurt in prices of tomato is a temporary s...,https://indianexpress.com/article/business/eco...,business
1999,Benchmark indices touch new highs: Sensex cros...,"With investors lapping up heavyweight stocks, ...",Domestic stock markets on Wednesday raced to f...,https://indianexpress.com/article/business/mar...,business

#**1. Lowercasing**
Convert every character in your text to lowercase. This ensures words like "Movie", "MOVIE", and "movie" are treated as the exact same word instead of three different ones.

In [14]:
df = df.astype(str)

In [15]:
df['headlines'] = df['headlines'].str.lower()
df['description'] = df['description'].str.lower()
df['content'] = df['content'].str.lower()
df['url'] = df['url'].str.lower()
df['category'] = df['category'].str.lower()

In [16]:
df

,headlines,description,content,url,category
0,nirmala sitharaman to equal morarji desai’s re...,with the presentation of the interim budget on...,"sitharaman, the first full-time woman finance ...",https://indianexpress.com/article/business/bud...,business
1,"‘will densify network, want to be at least no....","'in terms of market share, we aim to double it...",the merger of tata group’s budget airlines air...,https://indianexpress.com/article/business/avi...,business
2,air india group to induct an aircraft every si...,air india currently has 117 operational aircra...,the air india group plans to induct one aircra...,https://indianexpress.com/article/business/avi...,business
3,red sea woes: exporters seek increased credit ...,rising attacks forced shippers to consider the...,indian exporters have asked the central govern...,https://indianexpress.com/article/business/red...,business
4,air india group to induct a plane every 6 days...,"apart from fleet expansion, 2024 will also see...",the air india group plans to induct one aircra...,https://indianexpress.com/article/business/avi...,business
...,...,...,...,...,...
1995,"two official teams from india, eu to discuss c...",india raised these issues in the trade and tec...,india and the european union have constituted ...,https://indianexpress.com/article/business/two...,business
1996,"adani family sells $1 billion stake to gqg, ot...",the group's flagship adani enterprises ltd saw...,us-based boutique investment firm gqg partners...,https://indianexpress.com/article/business/com...,business
1997,housing sales up 8% in april-june period acros...,housing sales rose 8 per cent annually during ...,housing sales rose 8 per cent annually during ...,https://indianexpress.com/article/business/hou...,business
1998,spike in tomato prices temporary; rates will c...,the maximum price of rs 122 per kg has been re...,the spurt in prices of tomato is a temporary s...,https://indianexpress.com/article/business/eco...,business
1999,benchmark indices touch new highs: sensex cros...,"with investors lapping up heavyweight stocks, ...",domestic stock markets on wednesday raced to f...,https://indianexpress.com/article/business/mar...,business

#**2. Removal of HTML Tags & URLs**
Web-scraped data often contains leftover code (like <br>, <p>) and web links (http://...). Strip all of these out because they add noise without giving any real meaning to the text.

In [19]:
print(df.url.head(1))

0    https://indianexpress.com/article/business/bud...
Name: url, dtype: object

In [20]:
import re

# Regex to extract the main domain (e.g., example.com from http://www.example.com/path)
# It handles http/https and optional www. prefixes.
# The capturing group ([^/]+) will get everything between the protocol/www and the next slash or end of string.
url_pattern = r'(?:https?://)?(?:www\.)?([^/]+)'

# Apply the regex to the 'url' column and assign the extracted domain back to the 'url' column
df['url'] = df['url'].str.extract(url_pattern)

# Print the head of the updated url column to show the changes
print(df['url'].head())

0    indianexpress.com
1    indianexpress.com
2    indianexpress.com
3    indianexpress.com
4    indianexpress.com
Name: url, dtype: object

In [21]:
df.sample(10)

,headlines,description,content,url,category
82,"govt disburses rs 4,415 crore under pli scheme...","about rs 1,515 crore was disbursed in fy24 til...",the central government has disbursed incentive...,indianexpress.com,business
235,airtel to seek reversal of rs 24.9 lakh penalt...,the violation pertains to alleged irregular in...,bharti airtel on tuesday said it does not agre...,indianexpress.com,business
1522,freedom sale: get indian express digital acces...,freedom sale (independence day sale) 2023: let...,as india gears up to celebrate its 76th indepe...,indianexpress.com,business
1908,rbi asks banks to provide options for customer...,exemptions to govt entities from adverse conse...,the union cabinet wednesday approved the draft...,indianexpress.com,business
546,markets gain 0.55% in muhurat trading session,samvat 2079 was a year filled with global unce...,stock markets on sunday ushered in samvat 2080...,indianexpress.com,business
1910,jsw steel to replace hdfc in sensex from july 13,the company has launched invicto in three vari...,maruti suzuki india (msi) on wednesday launche...,indianexpress.com,business
936,sebi announces system to report demise of inve...,after receiving intimation about the demise of...,the securities and exchange board of india (se...,indianexpress.com,business
1851,global accounting firms set up shop in india’s...,"delta corp ltd sunk 23 per cent today, after t...",domestic markets ended in red on wednesday ahe...,indianexpress.com,business
1662,non-basmati white rice: imf ‘encourages’ india...,qatar's sovereign wealth fund is in talks to b...,qatar’s sovereign wealth fund is in early disc...,indianexpress.com,business
424,probe into assault allegation against gautam s...,"between november 12 and 28, the share price of...",a proxy advisory firm institutional investor a...,indianexpress.com,business

# **3. Removal of Punctuation & Special Characters**
Delete all commas, full stops, exclamation marks, and symbols (#, @, %, numbers). Keep only alphabetic letters and plain spaces.

In [ ]:
in

In [22]:
import re

# Define a function to remove punctuation and numbers, keeping only alphabetic characters and spaces
def remove_punctuation_numbers(text):
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove punctuation and special characters (keep only letters and spaces)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

# Apply the function to the relevant text columns
df['headlines'] = df['headlines'].apply(remove_punctuation_numbers)
df['description'] = df['description'].apply(remove_punctuation_numbers)
df['content'] = df['content'].apply(remove_punctuation_numbers)

# Display the head of the updated DataFrame to show the changes in the cleaned columns
print(df[['headlines', 'description', 'content']].head())

                                           headlines  \
0  nirmala sitharaman to equal morarji desais rec...
1  will densify network want to be at least no  i...
2  air india group to induct an aircraft every si...
3  red sea woes exporters seek increased credit a...
4  air india group to induct a plane every  days ...

                                         description  \
0  with the presentation of the interim budget on...
1  in terms of market share we aim to double it b...
2  air india currently has  operational aircraft ...
3  rising attacks forced shippers to consider the...
4  apart from fleet expansion  will also see air ...

                                             content
0  sitharaman the first fulltime woman finance mi...
1  the merger of tata groups budget airlines air ...
2  the air india group plans to induct one aircra...
3  indian exporters have asked the central govern...
4  the air india group plans to induct one aircra...

# **4. Tokenization**
Break down the continuous string of text into individual words or "tokens." For example, "I love movies" becomes ['i', 'love', 'movies'].

In [25]:
import nltk
from nltk.tokenize import word_tokenize

# Ensure the 'punkt_tab' tokenizer is downloaded. It's idempotent, so it won't re-download if already present.
nltk.download('punkt_tab', quiet=True)

# Define a function to tokenize text, handling potential non-string inputs
def tokenize_text(text):
    if isinstance(text, str):
        return word_tokenize(text)
    return []

# Apply tokenization to the relevant text columns
df['headlines_tokens'] = df['headlines'].apply(tokenize_text)
df['description_tokens'] = df['description'].apply(tokenize_text)
df['content_tokens'] = df['content'].apply(tokenize_text)

# Display the head of the updated DataFrame with new tokenized columns
print(df[['headlines', 'headlines_tokens', 'description', 'description_tokens', 'content', 'content_tokens']].head())

                                           headlines  \
0  nirmala sitharaman to equal morarji desais rec...
1  will densify network want to be at least no  i...
2  air india group to induct an aircraft every si...
3  red sea woes exporters seek increased credit a...
4  air india group to induct a plane every  days ...

                                    headlines_tokens  \
0  [nirmala, sitharaman, to, equal, morarji, desa...
1  [will, densify, network, want, to, be, at, lea...
2  [air, india, group, to, induct, an, aircraft, ...
3  [red, sea, woes, exporters, seek, increased, c...
4  [air, india, group, to, induct, a, plane, ever...

                                         description  \
0  with the presentation of the interim budget on...
1  in terms of market share we aim to double it b...
2  air india currently has  operational aircraft ...
3  rising attacks forced shippers to consider the...
4  apart from fleet expansion  will also see air ...

                                  description_tokens  \
0  [with, the, presentation, of, the, interim, bu...
1  [in, terms, of, market, share, we, aim, to, do...
2  [air, india, currently, has, operational, airc...
3  [rising, attacks, forced, shippers, to, consid...
4  [apart, from, fleet, expansion, will, also, se...

                                             content  \
0  sitharaman the first fulltime woman finance mi...
1  the merger of tata groups budget airlines air ...
2  the air india group plans to induct one aircra...
3  indian exporters have asked the central govern...
4  the air india group plans to induct one aircra...

                                      content_tokens
0  [sitharaman, the, first, fulltime, woman, fina...
1  [the, merger, of, tata, groups, budget, airlin...
2  [the, air, india, group, plans, to, induct, on...
3  [indian, exporters, have, asked, the, central,...
4  [the, air, india, group, plans, to, induct, on...

#**5. Removal of Stopwords**
Filter out high-frequency grammar words that carry almost no semantic value for NLP models—such as "is", "the", "at", "and", or "which".

In [27]:
import nltk
from nltk.corpus import stopwords

# Download the 'stopwords' corpus if not already downloaded. It's idempotent.
nltk.download('stopwords', quiet=True)

# Get the English stopwords list
stop_words = set(stopwords.words('english'))

# Define a function to remove stopwords from a list of tokens
def remove_stopwords(tokens):
    if isinstance(tokens, list):
        return [word for word in tokens if word not in stop_words]
    return tokens

# Apply the function to the tokenized columns
df['headlines_tokens'] = df['headlines_tokens'].apply(remove_stopwords)
df['description_tokens'] = df['description_tokens'].apply(remove_stopwords)
df['content_tokens'] = df['content_tokens'].apply(remove_stopwords)

print("Stopwords successfully removed from 'headlines_tokens', 'description_tokens', and 'content_tokens'.")
print("\nHere's a peek at the updated tokenized columns:")
print(df[['headlines_tokens', 'description_tokens', 'content_tokens']].head())

Stopwords successfully removed from 'headlines_tokens', 'description_tokens', and 'content_tokens'.

Here's a peek at the updated tokenized columns:
                                    headlines_tokens  \
0  [nirmala, sitharaman, equal, morarji, desais, ...
1  [densify, network, want, least, city, pair, ai...
2  [air, india, group, induct, aircraft, every, s...
3  [red, sea, woes, exporters, seek, increased, c...
4  [air, india, group, induct, plane, every, days...

                                  description_tokens  \
0  [presentation, interim, budget, february, nirm...
1  [terms, market, share, aim, double, segments, ...
2  [air, india, currently, operational, aircraft,...
3  [rising, attacks, forced, shippers, consider, ...
4  [apart, fleet, expansion, also, see, air, indi...

                                      content_tokens
0  [sitharaman, first, fulltime, woman, finance, ...
1  [merger, tata, groups, budget, airlines, air, ...
2  [air, india, group, plans, induct, one, aircra...
3  [indian, exporters, asked, central, government...
4  [air, india, group, plans, induct, one, aircra...

In [28]:
df.head()

,headlines,description,content,url,category,headlines_tokens,description_tokens,content_tokens
0,nirmala sitharaman to equal morarji desais rec...,with the presentation of the interim budget on...,sitharaman the first fulltime woman finance mi...,indianexpress.com,business,"[nirmala, sitharaman, equal, morarji, desais, ...","[presentation, interim, budget, february, nirm...","[sitharaman, first, fulltime, woman, finance, ..."
1,will densify network want to be at least no i...,in terms of market share we aim to double it b...,the merger of tata groups budget airlines air ...,indianexpress.com,business,"[densify, network, want, least, city, pair, ai...","[terms, market, share, aim, double, segments, ...","[merger, tata, groups, budget, airlines, air, ..."
2,air india group to induct an aircraft every si...,air india currently has operational aircraft ...,the air india group plans to induct one aircra...,indianexpress.com,business,"[air, india, group, induct, aircraft, every, s...","[air, india, currently, operational, aircraft,...","[air, india, group, plans, induct, one, aircra..."
3,red sea woes exporters seek increased credit a...,rising attacks forced shippers to consider the...,indian exporters have asked the central govern...,indianexpress.com,business,"[red, sea, woes, exporters, seek, increased, c...","[rising, attacks, forced, shippers, consider, ...","[indian, exporters, asked, central, government..."
4,air india group to induct a plane every days ...,apart from fleet expansion will also see air ...,the air india group plans to induct one aircra...,indianexpress.com,business,"[air, india, group, induct, plane, every, days...","[apart, fleet, expansion, also, see, air, indi...","[air, india, group, plans, induct, one, aircra..."

In [30]:
columns_to_drop = ['headlines', 'description', 'content']
df = df.drop(columns=columns_to_drop)

# Define the new order of columns: tokenized columns first, then others
tokenized_cols = ['headlines_tokens', 'description_tokens', 'content_tokens']
other_cols = [col for col in df.columns if col not in tokenized_cols]

# Combine and reorder
new_column_order = tokenized_cols + other_cols
df = df[new_column_order]

print("Original 'headlines', 'description', and 'content' columns removed, and tokenized columns reordered to the front.")
print("\nHere's the head of your updated DataFrame:")
print(df.head())

KeyError: "['headlines', 'description', 'content'] not found in axis"

In [31]:
df.head()

,headlines_tokens,description_tokens,content_tokens,url,category
0,"[nirmala, sitharaman, equal, morarji, desais, ...","[presentation, interim, budget, february, nirm...","[sitharaman, first, fulltime, woman, finance, ...",indianexpress.com,business
1,"[densify, network, want, least, city, pair, ai...","[terms, market, share, aim, double, segments, ...","[merger, tata, groups, budget, airlines, air, ...",indianexpress.com,business
2,"[air, india, group, induct, aircraft, every, s...","[air, india, currently, operational, aircraft,...","[air, india, group, plans, induct, one, aircra...",indianexpress.com,business
3,"[red, sea, woes, exporters, seek, increased, c...","[rising, attacks, forced, shippers, consider, ...","[indian, exporters, asked, central, government...",indianexpress.com,business
4,"[air, india, group, induct, plane, every, days...","[apart, fleet, expansion, also, see, air, indi...","[air, india, group, plans, induct, one, aircra...",indianexpress.com,business

#**6. Text Normalization (Stemming or Lemmatization)**
Reduce remaining words to their base or root form so your model recognizes different variations of a single word:

Stemming: Chops off word endings coarsely (e.g., "running", "ran", "runs" → "run").

Lemmatization: Uses a dictionary lookup to resolve words to their true linguistic base (e.g., "better" → "good").

In [32]:
import nltk
from nltk.stem import WordNetLemmatizer

# Download necessary NLTK data for lemmatization
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

# Initialize the WordNet Lemmatizer
lemmatizer = WordNetLemmatizer()

# Define a function to lemmatize a list of tokens
def lemmatize_tokens(tokens):
    if isinstance(tokens, list):
        return [lemmatizer.lemmatize(word) for word in tokens]
    return tokens

# Apply lemmatization to the tokenized columns
df['headlines_tokens'] = df['headlines_tokens'].apply(lemmatize_tokens)
df['description_tokens'] = df['description_tokens'].apply(lemmatize_tokens)
df['content_tokens'] = df['content_tokens'].apply(lemmatize_tokens)

print("Text normalization (lemmatization) applied to 'headlines_tokens', 'description_tokens', and 'content_tokens'.")
print("\nHere's a peek at the updated tokenized columns after lemmatization:")
print(df[['headlines_tokens', 'description_tokens', 'content_tokens']].head())

Text normalization (lemmatization) applied to 'headlines_tokens', 'description_tokens', and 'content_tokens'.

Here's a peek at the updated tokenized columns after lemmatization:
                                    headlines_tokens  \
0  [nirmala, sitharaman, equal, morarji, desais, ...
1  [densify, network, want, least, city, pair, ai...
2  [air, india, group, induct, aircraft, every, s...
3  [red, sea, woe, exporter, seek, increased, cre...
4  [air, india, group, induct, plane, every, day,...

                                  description_tokens  \
0  [presentation, interim, budget, february, nirm...
1  [term, market, share, aim, double, segment, pe...
2  [air, india, currently, operational, aircraft,...
3  [rising, attack, forced, shipper, consider, lo...
4  [apart, fleet, expansion, also, see, air, indi...

                                      content_tokens
0  [sitharaman, first, fulltime, woman, finance, ...
1  [merger, tata, group, budget, airline, air, in...
2  [air, india, group, plan, induct, one, aircraf...
3  [indian, exporter, asked, central, government,...
4  [air, india, group, plan, induct, one, aircraf...

#**7. Rejoining**
#####(Optional Final Step)
Join your cleaned list of word tokens back into a single clean string per row. This leaves you with a neat clean_description column ready for feature extraction (like Bag of Words or TF-IDF).

In [33]:
df

,headlines_tokens,description_tokens,content_tokens,url,category
0,"[nirmala, sitharaman, equal, morarji, desais, ...","[presentation, interim, budget, february, nirm...","[sitharaman, first, fulltime, woman, finance, ...",indianexpress.com,business
1,"[densify, network, want, least, city, pair, ai...","[term, market, share, aim, double, segment, pe...","[merger, tata, group, budget, airline, air, in...",indianexpress.com,business
2,"[air, india, group, induct, aircraft, every, s...","[air, india, currently, operational, aircraft,...","[air, india, group, plan, induct, one, aircraf...",indianexpress.com,business
3,"[red, sea, woe, exporter, seek, increased, cre...","[rising, attack, forced, shipper, consider, lo...","[indian, exporter, asked, central, government,...",indianexpress.com,business
4,"[air, india, group, induct, plane, every, day,...","[apart, fleet, expansion, also, see, air, indi...","[air, india, group, plan, induct, one, aircraf...",indianexpress.com,business
...,...,...,...,...,...
1995,"[two, official, team, india, eu, discus, carbo...","[india, raised, issue, trade, technology, coun...","[india, european, union, constituted, two, tea...",indianexpress.com,business
1996,"[adani, family, sell, billion, stake, gqg, inv...","[group, flagship, adani, enterprise, ltd, saw,...","[usbased, boutique, investment, firm, gqg, par...",indianexpress.com,business
1997,"[housing, sale, apriljune, period, across, cit...","[housing, sale, rose, per, cent, annually, apr...","[housing, sale, rose, per, cent, annually, apr...",indianexpress.com,business
1998,"[spike, tomato, price, temporary, rate, cool, ...","[maximum, price, r, per, kg, reported, gorakhp...","[spurt, price, tomato, temporary, seasonal, ph...",indianexpress.com,business
1999,"[benchmark, index, touch, new, high, sensex, c...","[investor, lapping, heavyweight, stock, sensex...","[domestic, stock, market, wednesday, raced, fr...",indianexpress.com,business